### ISSUE TITLE
root password for mysql

### ISSUE THREAD

**Issue by phpguru** [Darkmantle-Vagrant/laravel#1]
Do you happen to remember what the root password is for the mysql instance running in this vagrant box? I ended up doing [this](https://dev.mysql.com/doc/refman/5.0/en/resetting-permissions.html) to reset it.

**Comment by darkmantle** [comment]
Not off the top of my head, however I'm releasing a new version over the next few days so I will make sure to include that.

**Comment by darkmantle** [comment]
Updating the vagrant box as I type this, make sure to update.
